#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running Type Check..."
pnpm type-check

echo "Running Biome Check..."
pnpm check

echo "Running Security Audit..."
pnpm audit --audit-level=high || {
  echo "❌ No se permite pushear con vulnerabilidades altas."
  exit 1
}

echo "Running Build..."
#pnpm build
